language: rust
dist: bionic
script:
  - 'if [ "$WITH_LOCK" != "true" ]; then cargo update; fi'
  - 'cargo build'
  - 'cargo test --all-features'
  - 'if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo build --all-features --all-targets; fi'
  - 'cargo build --manifest-path marked-cli/Cargo.toml --all-features'

# See https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

env: # important!
  global: RUSTFLAGS=-Dwarnings

matrix:
  include:
    - rust: 1.38.0
      env: WITH_LOCK=true
    - rust: 1.38.0
    - rust: 1.38.0
      os: windows
      env: WITH_LOCK=true
    - rust: stable
      env: WITH_LOCK=true
    - rust: nightly
      env: MAY_FAIL=true
  allow_failures:
    - env: MAY_FAIL=true
