[workspace]
members = [ "marked", "marked-cli" ]
exclude = [ "ammonia-compare", "marked-sanitizer" ]

[patch.crates-io]
"marked" = { path = "marked" }

[profile.release]
lto = "thin"
incremental = false

[profile.bench]
lto = "thin"
incremental = false
