[package]
name = "ammonia-compare"
publish = false
version = "0.0.1"
authors = ["David Kellum <dek-oss@gravitext.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
marked        = { version=">=0.2.0, <0.3", path="../marked" }
ammonia       = { version=">=3.1.0, <3.2" }
